### PR TITLE
Update icons

### PR DESCRIPTION
**Pull request by domyen**
- Update icon sizes for circular icons
- Add accessibility icon
- Change bitbucket icon to their new logo

### CODE REVIEW

**Comment by kylesuss** [comment]
The base for this should probably be `next` or `release`, but not `master`. When do you want it to go out?

**Comment by domyen** [comment]
@kylesuss we don't have `next` or `release` for SDS.

**Comment by kylesuss** [comment]
Haha. Wow. Sorry -- jumping around a lot this morn. Makes sense.

**Comment by kylesuss** [comment]
:rocket: PR was released in v5.0.1 :rocket:

**Pull request merged**
