### PR TITLE
Export marketing components

### PR DESCRIPTION
**Pull request by kylegach**
<details>
  <summary>📦 Published PR as canary version: <code>7.0.4-canary.322.4411ee0.0</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @storybook/design-system@7.0.4-canary.322.4411ee0.0
  # or 
  yarn add @storybook/design-system@7.0.4-canary.322.4411ee0.0
  ```
</details>

### CODE REVIEW

**Comment by kylegach** [comment]
@winkerVSbecks — Any idea what's up with Netlify? Looks like it's been failing in the same way quite often, but it sometimes works? 🤷‍♂️

**Comment by kylegach** [comment]
Hmm... this is trickier than I first thought. The distributed files do not contain the svg files in `src/images`, which are referenced by PageFooter. Apparently (I did some searching), prior to PageFooter, all svg files in that directory were only referenced in story files, so it hasn't been an issue until I attempted to distribute that component.

**Comment by winkerVSbecks** [comment]
@kylegach perhaps convert it into JSX https://svg2jsx.com/

**Comment by kylegach** [comment]
> @kylegach perhaps convert it into JSX https://svg2jsx.com/

Yeah, that's what I ended up doing, but in an automated way via https://react-svgr.com/docs/cli/.

This is truly ready for review now. I confirmed it via canary install in my local project.

**Review by winkerVSbecks — APPROVED** [review]
🌈 🙌🏽

**Pull request merged**
