### PR TITLE
Upgrade to 5.3-beta and simplified path separators

### PR DESCRIPTION
**Pull request by shilman**
- [x] Upgrade to 5.3-alpha
- [x] Upgrade path separators and set `showRoot`

### CODE REVIEW

**Comment by kylesuss** [comment]
Nice, thanks @shilman . What does the `showRoot` param do? Not obvious to me just from the changes in the PR and I can't find easy docs about what it is.

**Comment by shilman** [comment]
@kylesuss https://github.com/storybookjs/storybook/blob/next/docs/src/pages/configurations/options-parameter/index.md

**Comment by kylesuss** [comment]
@shilman nice. Thanks for the links. Do you think it makes sense for us to just embrace the new hierarchy and just leave off the `showRoots` stuff? It seems like we have to approve all new stories here anyway.

**Comment by ndelangen** [comment]
LGTM, merge?

**Comment by shilman** [comment]
@kylesuss Sorry I missed this. I think `showRoots` is necessary to get the old behavior. Without `showRoots`, all of these stories would be shown under a folder called `Design System`, which I don't think is what we want.

**Pull request merged**
