### PR TITLE
Port over Cardinal component from Chromatic

### PR DESCRIPTION
**Pull request by winkerVSbecks**
@domyen ported over as is. The only change is left aligning both small and large cardinal.

### CODE REVIEW

**Review by kylesuss — APPROVED** [review]
👍

**Comment by domyen** [comment]
If we want to preserve center alignment for Large cardinals on the BuildScreen and PullRequestScreen, would we override in the Chromatic project or should that be an option here?

**Comment by winkerVSbecks** [comment]
@domyen I would add a prop to control that.

**Comment by domyen** [comment]
lgtm! The naming structure changed so you might want to pull `master` and remove `Design System` from the component title.

**Review by domyen — APPROVED** [review]

**Comment by winkerVSbecks** [comment]
:rocket: PR was released in [`v5.3.0`](https://github.com/storybookjs/design-system/releases/tag/v5.3.0) :rocket:

**Pull request merged**
