### PR TITLE
upgraded to 5.3beta and added dependencies plugin

### PR DESCRIPTION
**Pull request by atanasster**
- upgraded to storybook 5.3 beta 
- added dependencies plugin

I was testing the dependencies plugin and made those changes anyway, 
No problem at all if you don't want to upgrade to 5.3 beta yet, or if the dependencies plugin is not desired.

### CODE REVIEW

**Comment by shilman** [comment]
@atanasster the current design takes up a lot of screen real estate:

Design_System___Avatar_-_Large_⋅_Storybook

how about merging both of these tables into a single table and using "sections" within the table to differentiate between dependencies & dependents:

InfoButton_-_Simple_⋅_Storybook

i think this would be considerably more compact and look better too!

**Comment by atanasster** [comment]
thanks @shilman great suggestion, the new table Sections look great. I have updated the plugin and bumped the package version:

grab14

**Comment by shilman** [comment]
@atanasster nice use of presets 👨‍🍳💋👌

**Comment by atanasster** [comment]
Thanks @ndelangen had suggested to use presets.
I updated the readme now also for a quick setup: https://github.com/atanasster/storybook-addon-deps

**Comment by domyen** [comment]
@atanasster now that the dust has settled on 5.3. Want to pick this back up? I'd love to link to SDS as an example of the dependency addon in your deps blog post.

**Comment by atanasster** [comment]
@domyen - done :)

**Comment by domyen** [comment]
@atanasster There are some merge conflicts, can you take another look?

**Comment by atanasster** [comment]
@domyen - I think I solved those merge conflicts, although merging is not my forte so crossing fingers :)

**Comment by domyen** [comment]
Nice thanks! @ndelangen we're getting a new error on this branch with the Chromatic GH Action that says [we need an app code](https://github.com/storybookjs/design-system/pull/125/checks?check_run_id=404025043). AFAICT we have a secret for this that's referenced in the workflow file. Could you sanity check our configuration?

**Comment by ndelangen** [comment]
it's from a fork, thus the secret isn't shared.

I'll open a PR making the app-code public asap

**Comment by ndelangen** [comment]
Please merge in master, to get the public app_code in this PR

**Comment by atanasster** [comment]
@ndelangen - is this me merging or @domyen merging?

**Comment by ndelangen** [comment]
Me I guess 🌞

**Comment by domyen** [comment]
Dope, this looks awesome!

**Comment by ghengeveld** [comment]
:rocket: PR was released in v4.0.0 :rocket:

**Pull request merged**
